---
title: "Chapter2_regression analysis"
author: "Rabbil Bhuiyan"
date: "11 November 2018"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# read the data
student2014 <- read.table("http://s3.amazonaws.com/assets.datacamp.com/production/course_2218/datasets/learning2014.txt", sep = ",", header=TRUE)

# dimension of the data
dim(student2014)

#structure of the data
str(student2014)
```
# description of the data:
#The data has 166 observation and 7 variables namely gender, age, attitude, deep, stra, surf and points.

#summary of the data

```{r cars}
summary(student2014)
summary(student2014$age)
#Acess the ggplot2 library
library(ggplot2)
# initialize plot with data and aesthetic mapping
p1 <- ggplot(student2014, aes(x = attitude, y = points, col = gender))

# define the visualization type (points)
p2 <- p1 + geom_point()

# draw the plot
p2

# add a regression line
p3 <- p2 + geom_smooth(method = "lm")

# add a main title and draw the plot
p4 <- p3 + ggtitle("Student's attitude versus exam points")
p4
# description of the output: the anlayis shows the descriptives of each variables.Then the plot of student attitude vs exam points for both male and female
```

## Creation of Plots


```{r pressure, echo=FALSE}
plot(student2014)
# output of the plot: this graph tells about the plots for all the variables; how each varables are corelated with others
```
```{r}
# a scatter plot of points versus attitude
library(ggplot2)


# fit a linear model
my_model <- lm(points ~ attitude + stra + surf, data = student2014)

# print out a summary of the model
summary(my_model)
#output: none of the varible estimates were significant. then we removed one variable and check the significance level

# fit a linear model with removing one variable
my_model1 <- lm(points ~ attitude + stra, data = student2014)

# print out a summary of the model
summary(my_model1)

# fit a linear model removing another variable
my_mode2 <- lm(points ~ attitude + surf, data = student2014)

# print out a summary of the model
summary(my_mode2)

#Output: In all cases the attitude variable was signficanlty correlated with the dependent variable points


```
```{r}
#regression model validation

# regression model with multiple explanatory variables
my_model1 <- lm(points ~ attitude + stra, data = student2014)

# draw diagnostic plots 
par(mfrow = c(2,2))
plot(my_model1, which = c(1,2,5))
#description of the model validation
#From the resifual vs fitted validation model we see no clear pattern of the data- random distribution of data and it means the validation of quite good and thus the model parameter estimates. In the second  method, the q-q plot shows that the values are almost distributed along the line which mean good fit of the model. In the third validation model, we also see no outlier and thus the liverage is not high which means good fit of the model.
```




Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
